### ISSUE TITLE
📝 Feedback page and navbar header need new CTAs

### ISSUE THREAD

**Issue by azigler** [mattermost/mattermost-ai-site#4]
Problem
===
- The new feedback page has links to `focalboard`
- Forum CTA is duplicated in the header nav and the feedback page while the community channel is in neither.

Proposed solution
===
- Change "Feedback" to "Get Involved" and update the copy to reflect
- Drop the "forum" header nav link so that it's only "[mattermost-ai-framework](https://github.com/mattermost/mattermost-ai-framework) [mattermost-plugin-ai](https://github.com/mattermost/mattermost-plugin-ai) [Docs](https://docs.mattermost.com/about/mattermost-customizable-ai-bot-framework.html) [Get Involved](https://ai.mattermost.com/feedback)"
- Update "Get Involved" page links. Here's a possible structure with just two CTAs, to improve focus:
  - ["AI Exchange"](https://community.mattermost.com/core/channels/ai-exchange) Mattermost community server channel
  - ["AI Frameworks"](https://forum.mattermost.com/c/ai-frameworks/40) Mattermost community forums

**Comment by asaadmahmood** [comment]
@azigler The second AI frameworks link is pointing to:
https://github.com/mattermost/focalboard/issues

**Comment by azigler** [comment]
@asaadmahmood Fixed now!
