### ISSUE TITLE
🔎 Blog post og image is missing

### ISSUE THREAD

**Issue by azigler** [mattermost/mattermost-ai-site#5]
Problem
===
Currently, blog posts do not have any og image when shared. Example:

<img width="779" alt="image" src="https://github.com/mattermost/mattermost-ai-site/assets/7295363/306ee212-ffc3-4657-8266-086e5fb6ce28">

Proposed solution
===
Ensure all pages have an `og:image` tag.

@asaadmahmood

**Comment by asaadmahmood** [comment]
@azigler Done.

**Comment by azigler** [comment]
@asaadmahmood Could you add the appropriate OG-like tags for Twitter, as well? https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

**Comment by asaadmahmood** [comment]
@azigler Added it.
